services:
  hermes-gateway:
    image: nousresearch/hermes-agent:latest
    container_name: hermes-gateway
    restart: unless-stopped
    command: gateway run
    ports:
      - "8642:8642"
    volumes:
      - ${HERMES_DATA_DIR:-~/.hermes}:/opt/data
    environment:
      - API_SERVER_ENABLED=true
      - API_SERVER_KEY=your-secret-key
      - BROWSER_CDP_URL=${CHROME_HOST:-http://host.docker.internal:9222}
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "2.0"

  hermes-dashboard:
    # image: nousresearch/hermes-agent:latest
    image: hermes-hudui:0.5.0
    container_name: hermes-dashboard
    restart: unless-stopped
    command: hermes-hudui --host 0.0.0.0 --port 9119
    ports:
      - "9119:9119"
    environment:
      - HERMES_HOME=/opt/data
    volumes:
      - ${HERMES_DATA_DIR:-~/.hermes}:/opt/data
  
#   open-webui:
#     image: ghcr.io/open-webui/open-webui:main
#     container_name: open-webui
#     restart: always
#     ports:
#       - "3000:8080"
#     environment:
#       - OPENAI_API_BASE_URL=http://host.docker.internal:8642/v1
#       - OPENAI_API_KEY=your-secret-key
#     extra_hosts:
#       - "host.docker.internal:host-gateway"
#     volumes:
#       - open-webui:/app/backend/data

# volumes:
#   open-webui:
